format = """
$status\
[](#7035b8)\
$username\
[](bg:#5434c2 fg:#7035b8)\
$directory\
[](fg:#5434c2 bg:#3737ab)\
$git_branch\
$git_status\
[](fg:#3737ab bg:#3453c2)\
$nodejs\
$rust\
[](fg:#3453c2 bg:#356eb8)\
$time\
[ ](fg:#356eb8)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[status]
map_symbol = true
disabled = false
sigint_symbol = "☠"
not_executable_symbol = ""

# You can also replace your username with a neat symbol like  to save some space
[username]
#show_always = true
style_user = "bg:#7035b8"
style_root = "bg:#7035b8"
format = '[$user ]($style)'

[directory]
style = "bg:#5434c2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#3737ab"
format = '[[ $symbol $branch ](bg:#3737ab)]($style)'

[git_status]
style = "bg:#3737ab"
format = '[[($all_status$ahead_behind )](bg:#3737ab)]($style)'

[nodejs]
symbol = ""
style = "bg:#3453c2"
format = '[[ $symbol ($version) ](bg:#3453c2)]($style)'

[rust]
symbol = ""
style = "bg:#3453c2"
format = '[[ $symbol ($version) ](bg:#3453c2)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#356eb8"
format = '[[ $time ](bg:#356eb8)]($style)'
